<a href="https://colab.research.google.com/github/slawekpl81/data_science_udemy/blob/master/ds_udemy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
dir(np)
help(np.array)

In [13]:
x = np.array([1, 3])
print(x)
print(f'type: {type(x)}')
print(f'ndim:{x.ndim}')
print(f'shape:{x.shape}')
print(f'size: {x.size}')
print(f'dtype: {x.dtype}')

[1 3]
type: <class 'numpy.ndarray'>
ndim:1
shape:(2,)
size: 2
dtype: int64


In [19]:
x = np.array([[1, 2], [-3, 1]])
x.shape

(2, 2)

In [25]:
x = np.array([[1, 2, 4], [4, 2, 1]])
x.shape

(2, 3)

In [26]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]], dtype='float'
)
x.dtype

dtype('float64')

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

In [ ]:
np.ones(shape=(4, 10), dtype='int')

In [ ]:
np.full(shape=(5, 5), dtype='int', fill_value=4)

In [ ]:
np.arange(5,100,6).reshape((8,2,1))

In [ ]:
np.arange(5,100,6).reshape((4, -1))

In [ ]:
np.linspace(start=0, stop=20, num=8)

In [ ]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A+B)
print(A-B)
print(A*B)
print(A/B)

In [ ]:
print(A+3)
print(3*A)
print(A+ 3*B)

In [ ]:
x = np.array([[1,3],[-2,0]])
y = np.array([[6,0],[-1,2]])
print(x*y)
print(np.dot(x,y))
print(x.dot(y))
print(y.dot(x))
print(x@y)

In [49]:
np.random.seed(0)

In [ ]:
np.random.randn(10)

In [ ]:
np.random.rand()

In [ ]:
np.random.randint(10)

In [ ]:
np.random.choice(range(100))

In [ ]:
data = np.arange(10)
np.random.shuffle(data)
data

In [ ]:
print(np.exp(1))
print(np.sqrt(16))
x=[1,2,3,4,5,0]
print(np.all(x))
print(np.any(x))

In [ ]:
a = np.random.rand(10)
print(a)
print(np.argmax(a))
print(a[np.argmax(a)])
print(np.argsort(a))

In [ ]:
print(f'max:{a.max()}')
print(f'min:{a.min()}')
print(f'mean:{a.mean()}')
print(f'median:{np.median(a)}')
print(f'standard:{np.std(a)}')

In [ ]:
a = np.arange(20)
a=a.reshape(4,5)
print(a)
print(a[:,1])

In [ ]:
for item in a.flat:
  print(item)

In [ ]:
print(a.ravel())
print(a.transpose())

In [106]:
a=np.arange(-10,10,0.5)
a=a.reshape(10,-1)
print(a)
print(a>0)
print(a[a>0])
print(np.bitwise_and(a>-5,a<5))
print(a[np.bitwise_and(a>-5,a<5)])

[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.
 9.5]
[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]
 [False False False False]]
[-4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.
  2.5  3.   3.5  4.   4.5]
