<a href="https://colab.research.google.com/github/slawekpl81/data_science_udemy/blob/master/ds_udemy_statystyka.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
np.set_printoptions(precision=2)

funkcje statystyczne 
https://github.com/krakowiakpawel9/data-science-bootcamp/blob/master/01_wprowadzenie/03_funkcje_statystyczne.ipynb

In [10]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
price

array([[  12.4,   12.8,   11.9,   12.6, 1000. ],
       [  12.5,   13. ,   11.7,   12.2, 2000. ],
       [  12.2,   13.4,   12.2,   13.2, 1500. ]])

In [11]:
price.sum()

4650.1

In [12]:
price.sum(axis=0) # sumowanie w kolumnie

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [13]:
price.sum(axis=1) # sumowanie w wierszu

array([1049.7, 2049.4, 1551. ])

In [ ]:
print(f'min: {np.min(price)}')
print(f'min: {np.min(price, axis=0)}')
print(f'max: {np.max(price)}')
print(f'max: {np.max(price, axis=0)}')
print(f'median: {np.median(price, axis=0)}')
print(f'mean: {np.mean(price, axis=0)}')
print(f'std: {np.std(price, axis=0)}')
print(f'var: {np.var(price, axis=0)}')