<a href="https://colab.research.google.com/github/slawekpl81/data_science_udemy/blob/master/ds_udemy_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

WEKTORY
https://github.com/krakowiakpawel9/data-science-bootcamp/blob/master/01_wprowadzenie/02_algebra_liniowa.ipynb

In [ ]:
v1 = np.array([5,1])

In [ ]:
#norma wektora 
np.linalg.norm(v1)

5.0990195135927845

In [ ]:
# odległość dwóch punktów
a=np.array([3,0])
b=np.array([0,4])
np.linalg.norm(a-b)

5.0

In [ ]:
a=np.array([3,0,1])
b=np.array([0,4,2])
np.linalg.norm(a-b)

5.0990195135927845

In [ ]:
#mnozenie macierzy
x = np.array([[5, 3], [3, 9]])
y = np.array([[1], [-1]])
z = np.dot(x,y)
z

array([[ 2],
       [-6]])

In [ ]:
x = np.array([[2, -1, 3],[3, 1, 0]])
y = np.array([[2, 1, -1],[0, -1, 2],[3, 2, 0]])
z = np.dot(x,y)
z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [3]:
# wyznacznik macierzy
a = np.array([[2,4],[-1,3]])
round(np.linalg.det(a))

10.0

In [4]:
# ślad macierzy
np.trace(a)

5

In [ ]:
# macierz jednostkowa
np.eye(5)

In [6]:
# macierz odwrotna
np.linalg.inv(a)

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [7]:
# macierz transponowana
np.transpose(a) # a.T

array([[ 2, -1],
       [ 4,  3]])

In [8]:
# rozwiazywanie układów równań
a = np.array([[2,4], [1,-1]])
b = np.array([10,-1])

a_inv = np.linalg.inv(a)
x = np.dot(a_inv, b)
x

array([1., 2.])